#!/usr/bin/env sh

echo "Husky pre-commit hook running..."
# Get the list of staged files
staged_files=$(git diff --name-only --cached --diff-filter=AM)

# If no staged files, exit
if [ -z "$staged_files" ]; then
    echo "No staged files to check."
    exit 0
fi

echo "Staged files:"
echo "$staged_files"

ISSUES_FOUND=0
CWD=$(pwd)

# Check if there are changes in /frontend
if echo "$staged_files" | grep -q "^frontend/"; then
    echo "Running frontend linting and formatting..."
    cd frontend
    if ! npx lint-staged; then
        ISSUES_FOUND=1
        echo "Frontend linting and formatting issues detected."
    fi
    cd "$CWD"
fi

# Check if there are changes in /api
if echo "$staged_files" | grep -q "^api/"; then
    echo "Running API formatting..."
    if ! docker info > /dev/null 2>&1; then
        echo "Docker is not running. Please start Docker and try again."
        exit 1
    fi
    if ! make format; then
        ISSUES_FOUND=1
        echo "API formatting issues detected."
    fi
fi

if [ "$ISSUES_FOUND" -eq 1 ]; then
    echo "If you want to skip this check, run 'git commit --no-verify'"
    echo "Please fix the issues and try again."
    exit 1
fi

# Re-add any auto-fixed changes
git add $staged_files
echo "Husky pre-commit hook completed successfully."
exit 0