name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - bqplot
  - ipycanvas
  - ipywidgets
  # TODO: use a different solver to resolve these deps
  # - requests
  # - json
  # - pprint
  # - xarray
  # - geojson
  # - matplotlib
  # - contextily
  # - plotly
  # - earthaccess
